---
## Used to determine the sunrise/sunset at the users location.
## lat and lng options are mandatory, utc defaults to 0
## example for Paris:
position:
  lat: 48.864716
  lng: 2.349014
  utc: 2

## Internal monitor is the one for a laptop.
## This is optional.
## The update_threshold denotes the increment or decrement of the update. Default=5
## The min_br denotes the lowest brightness to be set. Default=2
## The max_br denotes the highest brightness to be set. Default=100
internal_monitor:
  update_threshold: 5
  min_br: 3
  max_br: 95

## The app currently supports one external monitor.
## This is optional, to turn on external monitor, include these lines.
## The subparameters are the same as for internal
external_monitor:
  update_threshold: 10
  min_br: 0
  max_br: 40

## If no internal and external monitors are configured above, then
## the app will only run hooks at the specified time. If no hooks are
## specified, the app will consume your cpu with doing nothing.

## The sleep_time_s denotes the interval of the brightness update given in seconds.
## This timer is for both internal and external monitors if given
## default value is 5 minutes (300s)
updater:
  sleep_time_s: 600

## Bash script hooks can be provided to run at sunset or sunrise.
## This may be useful for changing day and night rice for example.
## The evening_time and morning_time denotes at which twilight or dawn you wish to run the scripts.
## Possible options are: astronomical, nautical, civil
## [evening, morning]_scripts are the one liner scripts to be run.
## They have two types: static and dynamic. The reason why this exists is that f.e. the app starts
## (probably) before the window manager is started and you can't restart the window manager before
## it is started (as in the example below). Therefore dynamic scripts are not executed after startup
## only when it changes from one state to the another.
## morning_on_startup to run the morning script on startup or not. If it is disabled no hook is
## executed at startup.
## Defaults:
## - morning_on_startup=false
## - evening_time=astronomical
## - morning_time=astronomical
## if no scripts given (evening_scripts_static, evening_scripts_dynamic, morning_scripts_static, morning_scripts_dynamic
## then the hooks are disabled.
hooks:
  morning_on_startup: true
  evening_time: nautical
  morning_time: nautical
  evening_scripts_static:
    - KITTY_DIR=~/.config/kitty/ bash -c 'readlink -f "$KITTY_DIR"kitty.conf | grep "morning" &> /dev/null && ln -fs "$KITTY_DIR"kitty_evening.conf "$KITTY_DIR"kitty.conf'
    - I3_DIR=~/.config/i3/ bash -c 'rm -f "$I3_DIR"config && cat "$I3_DIR"config.main "$I3_DIR"config_theme.evening > "$I3_DIR"config'
  evening_scripts_dynamic:
    - i3 reload
  morning_scripts_static:
    - KITTY_DIR=~/.config/kitty/ bash -c 'readlink -f "$KITTY_DIR"kitty.conf | grep "evening" &> /dev/null && ln -fs "$KITTY_DIR"kitty_morning.conf "$KITTY_DIR"kitty.conf'
    - I3_DIR=~/.config/i3/ bash -c 'rm -f "$I3_DIR"config && cat "$I3_DIR"config.main "$I3_DIR"config_theme.morning > "$I3_DIR"config'
  morning_scripts_dynamic:
    - i3 reload
...
